version: "3"
services:
  bse:
    image: file:1
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: base
    restart: always
    ports:
      - 8090:80
    networks:
      - mynetwork
  
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysqldb
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flamy
networks:
  mynetwork:

## Use this compose file